function h = setSettingsControls(h,channels)     
chs=numel(channels);
 for ch = 1:chs
    %panelSettings: buttons for settings and calibration
    %shift calibration for cy5
    h.pathCalibs = cell(chs, 1);
    h.calib = cell(chs, 1);
    h.loadCalib = cell(chs, 1);
    ypos=.92-.21*(ch-1);
    uicontrol( ...
        'Parent', h.panelSettings, ...
        'Style','text', ...
        'Units', 'normalized', ...
        'Position', [.02, ypos, .96, .06], ...
        'String', [channels{ch} 'shift calibration'], ...
        'HorizontalAlignment', 'left');
    h.pathCalib{ch} = uicontrol( ...
        'Parent', h.panelSettings, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [.02, ypos-.05, .96, .06], ...
        'String', '', ...
        'Callback', '', ...
        'BusyAction', 'cancel');
    cn.name=channels{ch};
    cn.val=ch;
    h.calib{ch} = uicontrol( ...
        'Parent', h.panelSettings, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [.02, ypos-.15, .49, .1], ...
        'String', 'New', ...
        'Callback', @newCalibration_Callback, ...
        'UserData',cn, ...
        'BusyAction', 'cancel');

    h.loadCalib{ch} = uicontrol( ...
        'Parent', h.panelSettings, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [.51, ypos-.15, .47, .1], ...
        'String', 'Load', ...
        'UserData',cn, ...
        'Callback', @loadCalibration_Callback, ...
        'BusyAction', 'cancel');
 end
end