function ax = im(ima,title)
if nargin < 2
    title='';
    nt='on';
else
    nt='off';
end
scr=get(0, 'ScreenSize');
pos=[scr(1:2)+scr(3:4).*0.05,scr(4).*0.85,scr(4).*0.85];
fig = figure( ...
        'Units', 'Pixel', ...
        'Position', pos, ...
        'Name', title, ...
        'MenuBar', 'none', ...
        'Toolbar', 'figure', ...
        'Color', get(0, 'defaultuicontrolbackgroundcolor'), ...
        'NumberTitle', nt, ...
        'Resize', 'on', ...
        'Visible', 'on');    
ax= axes('Parent', fig,'Units', 'normalized', ...
        'Position', [.0, .0, 1.0, 1.0]);
axis(ax,'off','image','ij','square');
if nargin>0
imshow(ima,[],'InitialMagnification','Fit','Parent',ax)
end
end