function ax = im(ima)
scr=get(0, 'ScreenSize');
pos=[scr(1:2)+scr(3:4).*0.05,scr(4).*0.85,scr(4).*0.85];
fig = figure( ...
        'Units', 'Pixel', ...
        'Position', pos, ...
        'Name', 'Nucleus Spot Counter', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'Color', get(0, 'defaultuicontrolbackgroundcolor'), ...
        'NumberTitle', 'off', ...
        'Resize', 'on', ...
        'Visible', 'on');    
ax= axes('Parent', fig,'Units', 'normalized', ...
        'Position', [.0, .0, 1.0, 1.0]);
axis(ax,'off','image','ij','square');
if nargin>0
imshow(ima,'InitialMagnification','Fit','Parent',ax)
end
end